galaxy_info:
  author: xNok
  description: Hardens OS for Dark K3s Stack
  company: Infra
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bookworm
  galaxy_tags: []

dependencies: []
