#################################################
# OR INFRA Role: K3s Server
#################################################
---
- name: Download K3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0700'

- name: Install K3s Server
  command: /tmp/k3s_install.sh
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_server_version }}"
    INSTALL_K3S_EXEC: "{{ k3s_server_extra_args }}"
  args:
    creates: /usr/local/bin/k3s

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Read node-token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_server_node_token_content

- name: Store node-token
  set_fact:
    k3s_server_token: "{{ k3s_server_node_token_content['content'] | b64decode | trim }}"
