#################################################
# OR INFRA Role: K3s Server
#################################################
---
- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0700'

- name: Ensure K3s config directory exists
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'

- name: Deploy K3s configuration
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    mode: '0644'
  notify: Restart K3s

- name: Check if K3s is installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_server_binary

- name: Check for legacy arguments in K3s service
  ansible.builtin.shell: |
    if [ -f /etc/systemd/system/k3s.service ]; then
      grep -q -- "--bind-address" /etc/systemd/system/k3s.service || exit 1
    else
      exit 1
    fi
  register: k3s_server_service_has_legacy_args
  changed_when: false
  failed_when: false
  when: k3s_server_binary.stat.exists

- name: Install K3s Server
  ansible.builtin.command: /tmp/k3s_install.sh
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_server_version }}"
    INSTALL_K3S_EXEC: "{{ k3s_server_extra_args }}"
  when: not k3s_server_binary.stat.exists or (k3s_server_service_has_legacy_args.rc is defined and k3s_server_service_has_legacy_args.rc == 0)
  notify: Restart K3s
  changed_when: true

- name: Verify K3s service is running
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true

- name: Wait for node-token
  ansible.builtin.wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    timeout: 300

- name: Read node-token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_server_node_token_content

- name: Store node-token
  ansible.builtin.set_fact:
    k3s_server_token: "{{ k3s_server_node_token_content['content'] | b64decode | trim }}"
