galaxy_info:
  author: xNok
  description: Manages Google Cloud Platform infrastructure using Terraform.
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - terraform
    - gcp
    - google
    - cloud
    - infrastructure

dependencies:
  - diodonfrost.terraform
