namespace: "xnok"
name: "infra_bootstrap_tools"
version: "1.0.2"  # Incrementing version
description: >
  A collection of Ansible roles for bootstrapping and managing self-hosted projects and homelabs.
  Includes roles for Docker, Docker Swarm, Terraform, and various utilities.
readme: "README.md"
authors:
  - "xNok <https://github.com/xNok>"
license:
  - "MIT"
tags:
  - collection
  - infrastructure
  - automation
  - devops
  - docker
  - swarm
  - terraform
  - cloud
  - digitalocean
  - homelab
  - selfhosted
repository: "https://github.com/xNok/infra-bootstrap-tools"
documentation: "https://github.com/xNok/infra-bootstrap-tools/blob/main/ansible/README.md"
homepage: "https://github.com/xNok/infra-bootstrap-tools"
